RecipeViewerEvents.removeEntries('item', (e) => {
    e.remove([
        'createcasing:chorium_ingot',
        'createcasing:creative_casing',
        'createcasing:creative_gearbox',
        'createcasing:vertical_creative_gearbox',
        'createcasing:creative_mixer',
        'createcasing:creative_press',
        'createcasing:creative_depot',
        'createcasing:creative_encased_chain_drive',
        'createcasing:creative_adjustable_chain_gearshift',
        'createcasing:creative_configurable_gearbox',
        'sophisticatedbackpacks:survival_infinity_upgrade',
        'sophisticatedbackpacks:infinity_upgrade',
        'sophisticatedbackpacks:stack_upgrade_omega_tier',
        'sophisticatedbackpacks:stack_upgrade_tier_4',
        'sophisticatedbackpacks:inception_upgrade',
        'create_extra_casing:rgb_casing',
        'create_d2d:burner',
        'create_d2d:gatling_breaker',
        'create_d2d:coal_piece',
        'create_d2d:diamond_shard',
        'create_d2d:lapis_lazuli_shard',
        'create_d2d:hydraulic_press',
        'create_d2d:blasting_sail',
        'create_d2d:smoking_sail',
        'create_d2d:haunting_sail',
        'create_d2d:splashing_sail',
        'create_d2d:stirling_engine',
        'create_d2d:sap_bucket',
        'create_d2d:pumpkin_milkshake_bucket',
        'create_d2d:glowberry_milkshake_bucket',
        'create_d2d:strawberry_milkshake_bucket',
        'create_d2d:vanilla_milkshake_bucket',
        'create_d2d:chocolate_milkshake_bucket',
        'create_dragons_plus:lime_dye_bucket',
        'create_dragons_plus:yellow_dye_bucket',
        'create_dragons_plus:orange_dye_bucket',
        'create_dragons_plus:red_dye_bucket',
        'create_dragons_plus:brown_dye_bucket',
        'create_dragons_plus:black_dye_bucket',
        'create_dragons_plus:gray_dye_bucket',
        'create_dragons_plus:light_gray_dye_bucket',
        'create_dragons_plus:white_dye_bucket',
        'create_dragons_plus:pink_dye_bucket',
        'create_dragons_plus:magenta_dye_bucket',
        'create_dragons_plus:purple_dye_bucket',
        'create_dragons_plus:blue_dye_bucket',
        'create_dragons_plus:light_blue_dye_bucket',
        'create_dragons_plus:cyan_dye_bucket',
        'create_dragons_plus:green_dye_bucket',
        'create_sa:brass_jetpack_chestplate',
        'create_sa:netherite_jetpack_chestplate',
        'create_sa:copper_jetpack_chestplate',
        'create_sa:andesite_jetpack_chestplate',
        'createsandpapers:brown_sand_paper',
        'createsandpapers:green_sand_paper',
        'createsandpapers:orange_sand_paper',
        'createsandpapers:windswept_sand_paper',
        'createsandpapers:black_sand_paper',
        'createsandpapers:quartzite_sand_paper',
        'createsandpapers:blue_sand_paper',
        'createsandpapers:violet_sand_paper',
        'createsandpapers:pink_sand_paper',
        'createsandpapers:venus_sand_paper',
        'createsandpapers:moon_sand_paper',
        'createsandpapers:mars_sand_paper',
        'createsandpapers:red_arid_sand_paper',
        'createsandpapers:arid_sand_paper',
        'createsandpapers:white_sand_paper',
        'createsandpapers:foamy_sand_paper',
        'createsandpapers:coral_sand_paper',
        'createsandpapers:soulless_sand_paper',
        'kubejs:nerf_enderman',
        'kubejs:incomplete_dragon_egg',
        'easy_villagers:farmer',
        'easy_villagers:iron_farm',
        'kubejs:incomplete_pale_oak_heart',
        'kubejs:incomplete_ominous_bottle',
        'mapperbase:flatter_hammer',
        'mapperbase:reinforced_flatter_hammer',
        'mapperbase:iron_plate'
    ])
});
RecipeViewerEvents.removeEntries('fluid', (e) => {
    e.remove('create_d2d:sap',)
    e.remove('create_d2d:pumpkin_milkshake')
    e.remove('create_d2d:glowberry_milkshake')
    e.remove('create_d2d:strawberry_milkshake')
    e.remove('create_d2d:vanilla_milkshake')
    e.remove('create_d2d:chocolate_milkshake')
    e.remove('create_dragons_plus:lime_dye')
    e.remove('create_dragons_plus:yellow_dye')
    e.remove('create_dragons_plus:orange_dye')
    e.remove('create_dragons_plus:red_dye')
    e.remove('create_dragons_plus:brown_dye')
    e.remove('create_dragons_plus:black_dye')
    e.remove('create_dragons_plus:gray_dye')
    e.remove('create_dragons_plus:light_gray_dye')
    e.remove('create_dragons_plus:white_dye')
    e.remove('create_dragons_plus:pink_dye')
    e.remove('create_dragons_plus:magenta_dye')
    e.remove('create_dragons_plus:purple_dye')
    e.remove('create_dragons_plus:blue_dye')
    e.remove('create_dragons_plus:light_blue_dye')
    e.remove('create_dragons_plus:cyan_dye')
    e.remove('create_dragons_plus:green_dye')
});
RecipeViewerEvents.removeCategories(e => {
    e.remove('create_dragons_plus:coloring')

});